Feature/2.x human report
alekzonder/porchmark pull request #10
Opened 2020-01-14 09:56 UTC by alekzonder

PR into https://github.com/mutantcornholio/porchmark/pull/4

2020-01-17 08:01 UTC, mutantcornholio requested changes

2020-01-17 08:01 UTC, mutantcornholio commented on src/lib/view.ts
> +        throw new Error('TableView not inited');
А какие тут вообще есть параметры инициализации? Конструктор пустой. Почему не создать объект при первом вызове?

2020-01-17 08:01 UTC, mutantcornholio commented on src/lib/config/default.ts
> -        {name: 'decodedBodySize'},
А с этими что?

2020-01-17 08:01 UTC, mutantcornholio commented on src/lib/config/types.ts
> +  name: 'q50' | 'q80' | 'q95' | 'stdev' | 'count';
Наверное, `sum`, а не `count`.

2020-01-17 08:01 UTC, mutantcornholio commented on src/lib/view.ts
> +    public renderFn: () => void = () => { throw new Error('renderFn not set'); };
а где используется переопределение renderFn?

2020-01-17 08:01 UTC, mutantcornholio commented on src/lib/view.ts
> +    get config() {
Зачем эти геттеры-сеттеры, если они ничего не делают?

2020-01-17 08:01 UTC, mutantcornholio commented on src/lib/view.ts
> +    protected spaceInsufficiency: number = 0;
ПРОТЕКТЕД

интересно, как ты планируешь тут наследование)

2020-01-17 08:36 UTC, alekzonder commented on src/lib/view.ts
> +    public renderFn: () => void = () => { throw new Error('renderFn not set'); };
тут задается снаружи

https://github.com/alekzonder/porchmark/pull/10/files/58b8d2fd0cf83c23692d662179a3ee214f5445ae#diff-f12cae9d7eba4fd3b33a36233aab7025R59

2020-01-17 08:36 UTC, alekzonder commented on src/lib/view.ts
> +    protected spaceInsufficiency: number = 0;
просто чтобы оно не автокомплитилось снаружи, если используешь объект класса

2020-01-17 08:36 UTC, alekzonder commented on src/lib/view.ts
> +    get config() {
у нас есть view в котором определяется box для логов

пару PR назад ты писал что просто выводить в stdout логи это не очень и нужно выводить их сразу в screen и box, чтобы интерфейс был одинаковым 

логирование происходит в logger в файл и сразу вo view.viewConsole

но в момент когда мы стартуем уже пишутся логи, например, если накрутить verbose, и хочется их видеть на экране, но при этом конфига еще нет

второй момент это типизация

для этого нужен getter - если все правильно инициализировано, то ошибка не выбросится и по типизации все ок

аналогично со screen и box

2020-01-17 08:42 UTC, alekzonder commented on src/lib/view.ts
> +        throw new Error('TableView not inited');
конфига еще не существует, а логи писать в screen box надо и инициализировать все это тоже надо

вот тут отписался 

https://github.com/alekzonder/porchmark/pull/10#discussion_r367819909

2020-01-17 08:42 UTC, alekzonder commented on src/lib/config/default.ts
> -        {name: 'decodedBodySize'},
таблица в ширину сильно растет, пока убрал по дефолту, но это задается в config.metrics + через один пулл-реквест затащить вертикальную таблицу и там это будет нормально выглядеть

2020-01-17 08:42 UTC, alekzonder commented on src/lib/config/types.ts
> +  name: 'q50' | 'q80' | 'q95' | 'stdev' | 'count';
ну не, sum это другое

https://github.com/alekzonder/porchmark/pull/10/files/58b8d2fd0cf83c23692d662179a3ee214f5445ae#diff-44fbbd23db25ba3fdd2fded1fa0592f7R480

может быть length, но не sum

это чтобы отчете выводить количество итераций

2020-01-17 17:24 UTC, mutantcornholio commented on src/lib/view.ts
> +    get config() {
> но в момент когда мы стартуем и читаем конфиг уже пишутся логи, например, если накрутить verbose, и хочется их видеть на экране, но при этом конфига еще нет

> второй момент это типизация
для этого нужен getter - если все правильно инициализировано, то ошибка не выбросится и по типизации все ок

Значит ли это, что при попытке записать лог, приложение свалится с ошибкой?

2020-01-17 17:26 UTC, mutantcornholio commented on src/lib/config/default.ts
> -        {name: 'decodedBodySize'},
ок

2020-01-17 17:27 UTC, mutantcornholio commented on src/lib/config/types.ts
> +  name: 'q50' | 'q80' | 'q95' | 'stdev' | 'count';
ок

2020-01-17 17:27 UTC, mutantcornholio commented on src/lib/view.ts
> +    public renderFn: () => void = () => { throw new Error('renderFn not set'); };
ок

2020-01-20 04:43 UTC, alekzonder commented on src/lib/view.ts
> +    get config() {
нет, потому что screen создается и логи пишутся в него

для того чтобы полноценно создавать таблицу, с заголовками и прочим нужен конфиг, после resolveConfig устанавливаем конфиг и дальше уже работаем как обычно

2020-01-20 07:11 UTC, mutantcornholio approved these changes

2020-01-20 07:35 UTC, merged