Feature/2.x hooks, screenshots on record WPR
alekzonder/porchmark pull request #12
Opened 2020-01-27 11:24 UTC by alekzonder

PR into https://github.com/mutantcornholio/porchmark/pull/4

2020-01-28 11:19 UTC, mutantcornholio requested changes

2020-01-28 11:19 UTC, mutantcornholio commented on src/bin/porchmark-compare.ts
> +        logger.info('config', config);
это точно `info`?

2020-01-28 11:19 UTC, mutantcornholio commented on src/lib/comparison.ts
> +import fs from "fs-extra";
ты вроде кодстайл принёс, а не запускаешь его =)

2020-01-28 11:19 UTC, mutantcornholio commented on src/lib/comparison.ts
> +            await fs.mkdir(comparisonDir);
у `fs-extra` есть `ensureDir` или чот такое

2020-01-28 11:19 UTC, mutantcornholio commented on src/lib/helpers.ts
> +export function waitWhileLogFilesWriting(cb: () => void) {
можешь расписать конкретно какую проблему с какими логами ты тут решаешь?

2020-01-28 11:19 UTC, mutantcornholio commented on src/lib/wpr/index.ts
> +    let retry = 1;
Если начинаем с 1, то это `try`, а не `retry` :3

2020-01-28 11:19 UTC, mutantcornholio commented on src/lib/wpr/index.ts
> +                .then(() => page.screenshot({
Оно безусловное что ли?

2020-01-29 04:23 UTC, alekzonder commented on src/bin/porchmark-compare.ts
> +        logger.info('config', config);
я думаю полезно иметь целиком конфиг в логах, чтобы разбираться

можно переделать на debug, но он ничем не мешает

2020-01-29 04:37 UTC, alekzonder commented on src/lib/helpers.ts
> +export function waitWhileLogFilesWriting(cb: () => void) {
убрал

2020-01-29 04:47 UTC, alekzonder commented on src/lib/wpr/index.ts
> +                .then(() => page.screenshot({
да, когда WPR записывается один раз снимаем скриншот

чтобы в любой момент можно было посмотреть для конкретного WPR что там было на странице в момент записи

2020-01-29 04:48 UTC, alekzonder commented on src/lib/wpr/index.ts
> +    let retry = 1;
```suggestion
    let retry = 0;
```

исправил

2020-01-29 04:48 UTC, alekzonder commented on src/lib/comparison.ts
> +import fs from "fs-extra";
добавил husky на pre-commit

2020-01-29 04:49 UTC, alekzonder commented
@mutantcornholio /fixed

2020-01-29 19:51 UTC, mutantcornholio commented on src/bin/porchmark-compare.ts
> +        logger.info('config', config);
А дефолтный уровень какой?

2020-01-29 19:52 UTC, mutantcornholio commented on src/lib/wpr/index.ts
> +                .then(() => page.screenshot({
А какой объём WPR и какой объём скриншотов?

2020-01-30 06:13 UTC, alekzonder commented on src/lib/wpr/index.ts
> +                .then(() => page.screenshot({
размер WPR зависит от страницы

для главной десктопа WPR-архив порядка 3Мб, размер full-скриншота порядка 600-650Кб

2020-01-30 15:18 UTC, mutantcornholio approved these changes

2020-01-30 15:36 UTC, merged