wpr module
alekzonder/porchmark pull request #4
Opened 2019-12-02 16:41 UTC by alekzonder

2019-12-02 17:02 UTC, mutantcornholio requested changes

2019-12-02 17:02 UTC, mutantcornholio commented on src/lib/wpr/WprAbstract.ts
> +export function checkProcessByPid(pid: number) {
Унеси в отдельный хэлпер, не относится это к записи WPR

2019-12-02 17:02 UTC, mutantcornholio commented on src/lib/wpr/WprAbstract.ts
> +export function sleep(ms: number) {
И это

2019-12-02 17:02 UTC, mutantcornholio commented on src/lib/wpr/WprAbstract.ts
> +        }
Чот ты занимаешься каким-то лишним хэндлингом всего. Посмотри в сторону `child_process.exec`

2019-12-02 17:07 UTC, alekzonder commented on src/lib/wpr/WprAbstract.ts
> +        }
exec же не позволяет stdout, stderr не позволяет пайпить, а там может быть много

только после завершения процесса

2019-12-02 17:10 UTC, alekzonder commented on src/lib/wpr/WprAbstract.ts
> +export function checkProcessByPid(pid: number) {
перенес

2019-12-02 17:57 UTC, mutantcornholio commented on src/lib/wpr/WprAbstract.ts
> +        }
Это всё что нужно? Если да, то мб давай это шеллом сделаем?)

2019-12-02 18:14 UTC, mutantcornholio requested changes

2019-12-02 18:14 UTC, mutantcornholio commented on src/lib/wpr/WprAbstract.ts
> +        const isAlive = checkProcessByPid(this.process.pid);
Вообще, это выглядит лишним. cp.on('exit',...) хватит всем.
Вот тут есть всякое, оттестированное: https://github.com/mutantcornholio/veendor/blob/master/src/lib/commandWrappers/helpers.ts

2019-12-02 18:14 UTC, mutantcornholio commented on src/lib/wpr/index.ts
> +    return new WprRecord(logger, config);
У нас уже есть функция `getLogger`, хватит его передавать значит

2019-12-02 18:14 UTC, mutantcornholio commented on src/lib/wpr/index.ts
> +        injectScripts: path.resolve(wprToolDir, 'deterministic.js'),
мы ожидаем другой набор bin, certFile и т.д.?

2019-12-03 02:35 UTC, alekzonder commented on src/lib/wpr/WprAbstract.ts
> +        const isAlive = checkProcessByPid(this.process.pid);
ну так ты стартуешь и он должен жить во время теста, то есть нужно удостоверится что процесс жив

```
await process.start();

// тут знаем что процесс живет и работает - запускаем браузер и едем дальше

```

в случае с exec нужно будет обрабатывать это после, конечно в идеале нужно ожидать что любой процесс может отвалится в любой момент

тем более что стартует он не прям мгновенно и нужно некторое время подождать пока стартует

вообще по-хорошему нужно как-то проверять что именно этот процесс поднялся и слушает именно эти порты, потому что в случае если порты заняты, он не падает, он в лог пишет порты заняты и висит дальше, что очень криво выглядит, поднялся он или нет можно по логам понять

2019-12-03 02:37 UTC, alekzonder commented on src/lib/wpr/index.ts
> +        injectScripts: path.resolve(wprToolDir, 'deterministic.js'),
там порты и путь к wpr archive, немного исправил общее вынес в общий baseConfig

2019-12-03 02:40 UTC, alekzonder commented on src/lib/wpr/index.ts
> +    return new WprRecord(logger, config);
что плохого? есть класс он принимает логгер, есть два метода, они берут общий логгер и передают в класс при инициализации, в итоге в коде будут использованы эти методы и логгер будет общий, а если понадобится, то можно и кастомный передать  😕

2019-12-03 07:34 UTC, mutantcornholio commented on src/lib/wpr/index.ts
> +    return new WprRecord(logger, config);
Объясни, зачем этот класс можно создавать с кастомным логгером.
Вся идея этой функции в том, чтобы не передавать инстансы логгера больше, а из любого модуля иметь возможность получить по месту

2019-12-03 07:36 UTC, mutantcornholio commented on src/lib/wpr/index.ts
> +        injectScripts: path.resolve(wprToolDir, 'deterministic.js'),
Ну вопрос скорее в том, хотим ли мы давать это переопределять, или мб просто зашьём пути внутри?

2019-12-03 07:38 UTC, mutantcornholio commented on src/lib/wpr/WprAbstract.ts
> +        const isAlive = checkProcessByPid(this.process.pid);
> то есть нужно удостоверится что процесс жив

Ну ты и так знаешь что он жив, если он не бросил события выхода

2019-12-03 08:31 UTC, alekzonder commented on src/lib/wpr/index.ts
> +        injectScripts: path.resolve(wprToolDir, 'deterministic.js'),
ну они же и так зашиты

вызывается так

```
contst process = createWprRecordProcess({
  wprArchiveFilepath: 'test.wprgo',
  httpPort: 123,
  httpsPort: 1234,
  stdoutFilepath: 'stdout.log',
  stderrFilepath: 'stderr.log'

});

```

снаружи никаких путей к бинарям и сертификатам не передаем, все внутри модуля

2019-12-03 08:53 UTC, alekzonder commented on src/lib/wpr/WprAbstract.ts
> +        const isAlive = checkProcessByPid(this.process.pid);
убрал checkProcessByPid, spawn оставил

https://github.com/alekzonder/porchmark/pull/4/commits/afbde4408275bc45b8e3f77d5fd697e0643b57a4#diff-1e21f36ec759bbdb667542323992aa51R50

2019-12-03 08:53 UTC, alekzonder commented on src/lib/wpr/index.ts
> +    return new WprRecord(logger, config);
переделал на глобальный логгер

2019-12-03 08:54 UTC, alekzonder commented on src/lib/wpr/WprAbstract.ts
> +        }
оставил spawn, с on('close') в методе start получается по сути то же самое + добавил on('error')

2019-12-03 11:50 UTC, mutantcornholio requested changes

2019-12-03 11:50 UTC, mutantcornholio commented on src/lib/wpr/WprAbstract.ts
> +        logger.debug(`sleep ${sleepTimeout}ms`);
А зачем слип остался?

2019-12-03 15:40 UTC, alekzonder commented on src/lib/wpr/WprAbstract.ts
> +        logger.debug(`sleep ${sleepTimeout}ms`);
он стартует не сразу, если сразу стартовать браузер можно получить фейл на первой странице

можно конечно чекать порты, конечно чтобы наверняка, но нужно ли

2019-12-03 17:31 UTC, mutantcornholio commented on src/lib/wpr/WprAbstract.ts
> +        logger.debug(`sleep ${sleepTimeout}ms`);
Асинхронной обратной связи заиметь не сможем?

2019-12-03 17:32 UTC, mutantcornholio commented on src/lib/wpr/WprAbstract.ts
> +        logger.debug(`sleep ${sleepTimeout}ms`);
а, лол, ты удалил слипы уже)

2019-12-03 17:33 UTC, mutantcornholio approved these changes

2019-12-03 17:34 UTC, merged