puppeteer module integration
alekzonder/porchmark pull request #6
Opened 2019-12-06 09:17 UTC by alekzonder

2019-12-09 17:30 UTC, mutantcornholio requested changes

2019-12-09 17:30 UTC, mutantcornholio commented on src/lib/logger.ts
> +export let loggerInstance: Logger;
Зачем, если есть getLogger?

2019-12-09 17:30 UTC, mutantcornholio commented on src/lib/config/commanderArgv.ts
> +            logger.fatal('error on read config', e);
очень странно видеть `error on read config` при `MODULE_NOT_FOUND`

2019-12-09 17:30 UTC, mutantcornholio commented on src/lib/config/commanderArgv.ts
> +    } else if (fs.existsSync(porchmarkConfPath)) {
Зачем `existsSync` вообще? Просто пытайся выполнять и всё. `exists` вообще надо очень аккуратно использовать. Почитай, почему он [deprecated](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_exists_path_callback)

2019-12-09 17:30 UTC, mutantcornholio commented on src/lib/config/commanderArgv.ts
> +            logger.error(error);
А какого рода здесь могут быть ошибки, и почему они не критичные?

2019-12-09 17:30 UTC, mutantcornholio commented on src/lib/config/index.ts
> +    return schema.validateAsync(rawConfig, options) as any as IConfig;
ээ, оно ж промис возвращает

2019-12-10 11:56 UTC, alekzonder commented on src/lib/logger.ts
> +export let loggerInstance: Logger;
сам не понял, убрал

2019-12-10 12:05 UTC, alekzonder commented on src/lib/config/commanderArgv.ts
> +            logger.fatal('error on read config', e);
переделал

2019-12-10 12:07 UTC, alekzonder commented on src/lib/config/commanderArgv.ts
> +    } else if (fs.existsSync(porchmarkConfPath)) {
убрал existsSync, поменял на else

2019-12-10 12:08 UTC, alekzonder commented on src/lib/config/commanderArgv.ts
> +            logger.error(error);
согласен,  logger.fatal

2019-12-10 12:09 UTC, alekzonder commented on src/lib/config/index.ts
> +    return schema.validateAsync(rawConfig, options) as any as IConfig;
исправил

2019-12-10 18:01 UTC, mutantcornholio commented on src/lib/config/index.ts
> +const validateConfig = (rawConfig: any): Promise<IConfig> => {
А нигде не надо было await добавить?

2019-12-10 18:02 UTC, mutantcornholio approved these changes
больше вопросов нет

2019-12-11 02:45 UTC, alekzonder commented on src/lib/config/index.ts
> +const validateConfig = (rawConfig: any): Promise<IConfig> => {
schema.validateAsync возвращает Promise, так что все норм

2019-12-11 02:45 UTC, merged