Feature/2.x wpr integration
alekzonder/porchmark pull request #7
Opened 2019-12-09 06:47 UTC by alekzonder

2019-12-10 12:21 UTC, alekzonder commented
@mutantcornholio

2019-12-16 11:49 UTC, mutantcornholio requested changes

2019-12-16 11:49 UTC, mutantcornholio commented on src/lib/logger.ts
> +export function setLogToConsole(bool: boolean) {
Мне кажется, это должны быть параметры у `createLogger`. Или есть определённые причины делать именно так?

2019-12-16 11:49 UTC, mutantcornholio commented on src/lib/findFreePorts/index.ts
> +    host: '127.0.0.1',
Это будет иметь проблемы в ipv6-only хостах.
Давай попробуем с localhost

2019-12-16 11:49 UTC, mutantcornholio commented on src/lib/puppeteer/runCheck.ts
> +            const [browser] = await Promise.all([launchBrowser(launchOptions), wprReplay.start()]);
wprReplay умеет сам ждать браузер?

2019-12-16 11:49 UTC, mutantcornholio commented on src/lib/workerFarm.ts
> +        waitForCompleteInterval = setInterval(() => {
Почему не чистить его прям внутри `waitForComplete`?

2019-12-16 13:08 UTC, alekzonder commented on src/lib/logger.ts
> +export function setLogToConsole(bool: boolean) {
когда идет сравнение и выводится таблица сравнения, то логирование начинает ее перекрывать, а раз логгер глобальный, то я перед тем как выводить таблицу отключаю вывод в консоль и он пишет только в файл, после того как сравнение завершено, включаю обратно

2019-12-16 13:17 UTC, alekzonder commented on src/lib/puppeteer/runCheck.ts
> +            const [browser] = await Promise.all([launchBrowser(launchOptions), wprReplay.start()]);
нет, он просто как прокси работает и  с этим уже по ходу возникли проблемы в сандбокс таске

не всегда дожидается wpr, еще будем смотреть

2019-12-16 13:29 UTC, alekzonder commented on src/lib/workerFarm.ts
> +        waitForCompleteInterval = setInterval(() => {
я в последующих PR это использовал, нужно останавливать интервал отдельно, если там не пригодится переместим

2019-12-16 13:55 UTC, alekzonder commented on src/lib/findFreePorts/index.ts
> +    host: '127.0.0.1',
исправил

2019-12-16 13:55 UTC, alekzonder commented
@mutantcornholio /fixed

2019-12-17 04:28 UTC, mutantcornholio commented on src/lib/logger.ts
> +export function setLogToConsole(bool: boolean) {
Чот не то. Я же специально делал логгирование **под** таблицей. Эта логика похерилась?

2019-12-17 04:30 UTC, mutantcornholio commented on src/lib/logger.ts
> +        level: 'trace',
Раз такие изменения пролезают, может нам надо в параметры это унести?

2019-12-17 12:21 UTC, alekzonder commented on src/lib/logger.ts
> +export function setLogToConsole(bool: boolean) {
нет она есть и используется, просто view поднимается позже, а логирование раньше, поэтому сделал так, можно совместить все это

крое этого нужен лог в файл обязательно а все остальное опционально

2019-12-18 03:05 UTC, alekzonder commented on src/lib/logger.ts
> +export function setLogToConsole(bool: boolean) {
переделал на viewConsole

2019-12-18 03:06 UTC, alekzonder commented on src/lib/logger.ts
> +        level: 'trace',
сделал config.logLevel и опцию `--verbose`

2019-12-19 06:26 UTC, alekzonder commented
@mutantcornholio fixed

2019-12-24 09:02 UTC, merged