Feature/2.x wpr integration part 2
alekzonder/porchmark pull request #8
Opened 2019-12-24 09:30 UTC by alekzonder

сравнение через несколько  собранных wpr

2019-12-25 09:49 UTC, mutantcornholio requested changes

2019-12-25 09:49 UTC, mutantcornholio commented on src/lib/view.ts
> +    if (screen) {
А в каком случае это не true? Вроде если screen'а нету, то он создастся в начале метода

2019-12-25 09:49 UTC, mutantcornholio commented on src/lib/puppeteer/page.ts
> +        cacheEnabled: addThrottling ? options.cacheEnabled : true,
а почему эти опции зависят друг от друга?

2019-12-25 09:49 UTC, mutantcornholio commented on src/lib/puppeteer/runCheck.ts
>          viewConsole.error(e);
несколько смущает такая пара логов
мне кажется, такое может приводить к дублированию логов.
либо наоборот, недостатку логов в viewConsole. 

везде дёргать logger, а view подпишется на него?

UPD: а я его похоже изначально так и написал) видимо, здесь стоит убрать `viewConsole.error`?

2019-12-25 09:49 UTC, mutantcornholio commented on src/lib/dataProcessor.ts
> +    public increaseIterationCount() {
Выглядит довольно странно. Распиши мотивацию плиз за этим

2019-12-25 09:49 UTC, mutantcornholio commented on src/lib/view.ts
> +export function destroyScreenAndLogResults() {
распиши мотивацию и за этим тоже.
зачем нам убивать вьюху, и не выходить потом?

2019-12-25 09:49 UTC, mutantcornholio commented on src/lib/workerFarm.ts
>          viewConsole.error(error);
тут тоже дублирование логов

2019-12-25 09:49 UTC, mutantcornholio commented on src/bin/porchmark-compare.ts
> +async function startComparison(config: IConfig, comparison: IComparison) {
Может, раз оно разрослось, вообще в lib/ его?

2019-12-25 09:49 UTC, mutantcornholio commented on src/lib/wpr/select.ts
> +    const found = wprs.filter((wpr) => wpr.siteName === site.name && wpr.wprArchiveId === wprArchiveId);
`wprs.find()`?

2019-12-25 10:47 UTC, alekzonder commented on src/lib/view.ts
> +    if (screen) {
![Снимок экрана 2019-12-25 в 17 47 33](https://user-images.githubusercontent.com/286330/71443631-ac46d400-273e-11ea-8dbd-e4c04d374f07.png)

2019-12-25 11:02 UTC, alekzonder commented on src/lib/view.ts
> +    if (screen) {
да сейчас нет, нужно было до того как логи начали писаться во viewConsole

2019-12-25 11:02 UTC, alekzonder commented on src/lib/view.ts
> +export function destroyScreenAndLogResults() {
убрал, нужно было когда после каждого WPR убивался screen

2019-12-25 11:02 UTC, alekzonder commented on src/lib/workerFarm.ts
>          viewConsole.error(error);
заменил на logger.error, или убрал везде где использовались два

2019-12-25 11:02 UTC, alekzonder commented on src/lib/wpr/select.ts
> +    const found = wprs.filter((wpr) => wpr.siteName === site.name && wpr.wprArchiveId === wprArchiveId);
да

2019-12-25 11:09 UTC, alekzonder commented on src/lib/puppeteer/page.ts
> +        cacheEnabled: addThrottling ? options.cacheEnabled : true,
при записи WPR нужно быстро писать WPR без троттлинга, хотя сам по себе кэш нужно наоборот выключать при записи WPR

2019-12-25 11:09 UTC, alekzonder commented on src/lib/puppeteer/runCheck.ts
>          viewConsole.error(e);
да, я его убрал

2019-12-25 11:18 UTC, alekzonder commented on src/lib/dataProcessor.ts
> +    public increaseIterationCount() {
у нас на dataProcessor завязано завершение запуска воркеров (getNextSiteIndex в workerFarm)

https://github.com/alekzonder/porchmark/blob/35270e8c0c9d691e6d59bd3f1584fec47dfab922/src/lib/workerFarm.ts#L51

например,  нам нужно сравнить 3 WPR по 10 итераций на каждую

запускаем первый WPR - делаем 10 итераций, если increaseIterationCount не делать, то он перестанет запускать новые воркеры и все просто повиснет

поэтому после каждого WPR добавляем еще итераций

выглядит как костыль и по-хорошему нужно размотать эту логику, но она не меняется дальше поэтому можно позже сделать

2019-12-25 11:20 UTC, alekzonder commented on src/bin/porchmark-compare.ts
> +async function startComparison(config: IConfig, comparison: IComparison) {
в следующих ревью там эта же функция меняется, давай после следующего PR уберу в lib/

2019-12-25 11:24 UTC, mutantcornholio commented on src/lib/puppeteer/page.ts
> +        cacheEnabled: addThrottling ? options.cacheEnabled : true,
Тогда эт не зависимостями друг от друга ставить надо, а выставлять вот тут вторую опцию https://github.com/alekzonder/porchmark/blob/35270e8c0c9d691e6d59bd3f1584fec47dfab922/src/lib/wpr/index.ts#L106

2019-12-25 11:35 UTC, alekzonder commented on src/lib/puppeteer/page.ts
> +        cacheEnabled: addThrottling ? options.cacheEnabled : true,
ну кстати с другой стороны можно вообще все это убрать и сделать по месту

в recordWprArchives переопределение pageProfile - это как раз куда ты показал

```
const pageProfile = preparePageProfile(config);

pageProfile.cacheEnabled = false;
pageProfile.cpuThrottling = null;
```

2019-12-25 12:03 UTC, mutantcornholio commented on src/bin/porchmark-compare.ts
> +async function startComparison(config: IConfig, comparison: IComparison) {
Если важно пока оставить здесь, давай тогда тречить список доделок на «через PR» где-то?

2019-12-25 12:05 UTC, mutantcornholio commented on src/lib/dataProcessor.ts
> +    public increaseIterationCount() {
Мы же можем на каждый запуск WPR делать по новому DataProcessor'у?

2019-12-25 12:20 UTC, alekzonder commented on src/lib/dataProcessor.ts
> +    public increaseIterationCount() {
нам нужен общий отчет для разных WPR 

если делать на каждый запуск WPR свой dataProcessor, то нужно данные из предыдущего переносить

2019-12-25 12:21 UTC, alekzonder commented on src/bin/porchmark-compare.ts
> +async function startComparison(config: IConfig, comparison: IComparison) {
давай тут в description

https://github.com/mutantcornholio/porchmark/pull/4#issue-347506438

2019-12-25 12:41 UTC, mutantcornholio commented on src/bin/porchmark-compare.ts
> +async function startComparison(config: IConfig, comparison: IComparison) {
Годится)

2019-12-26 03:51 UTC, alekzonder commented on src/lib/puppeteer/page.ts
> +        cacheEnabled: addThrottling ? options.cacheEnabled : true,
переделал так

2019-12-26 03:59 UTC, alekzonder commented on src/lib/dataProcessor.ts
> +    public increaseIterationCount() {
@mutantcornholio оставляем так?

я вообще делал эту работу с воркерами по-другому - совсем прямолинейно

у каждого site свой итератор и они работают независимо, но тогда нет смысла в workersCount, потому что их будет столько же сколько и сайтов

https://github.com/mutantcornholio/porchmark/pull/3/files#diff-bce75583a17d5dcfa14c012337d2c779R3

думаю что такой подход лучше и по завершению всех ревью хочу вкрутить его сюда и сравнить результаты с workerFarm на примере простых страниц с циклами

https://alekzonder.github.io/test-metrics/00.html
https://alekzonder.github.io/test-metrics/100.html
https://alekzonder.github.io/test-metrics/1000.html

получается что вроде бы оба подхода похожи, но разница есть, потому что замеры этих страниц с workerFarm не показывают ту разницу, которую я получал ранее

2019-12-26 09:00 UTC, mutantcornholio commented on src/lib/dataProcessor.ts
> +    public increaseIterationCount() {
Идея выдачи воркерам сайта с самым меньшим количеством результатов в том, чтобы во время расчётов можно было видеть картину примерно равнозначную. А это единственное, на что влияет iterationCount
Я совершенно не помню, зачем я отдал эту роль DataProcessor'у. Давай мб унесём это в WorkerFarm, который уже знает об id сравнения и который по идее должен управлять такими вещами?

2019-12-30 06:56 UTC, alekzonder commented on src/lib/dataProcessor.ts
> +    public increaseIterationCount() {
перенес 

https://github.com/alekzonder/porchmark/pull/8/commits/f1ec7152444ae4bebb4cd116c51716263480e6b1

2019-12-30 10:58 UTC, mutantcornholio approved these changes

2019-12-30 10:59 UTC, merged