Feature/2.x page structure sizes
alekzonder/porchmark pull request #9
Opened 2019-12-30 11:10 UTC by alekzonder

https://github.com/mutantcornholio/porchmark/pull/4

2020-01-10 23:44 UTC, mutantcornholio requested changes

2020-01-10 23:44 UTC, mutantcornholio commented on src/lib/puppeteer/pageStructureSizes.ts
> +};
Учитывая, что ты всё равно исходник берёшь из браузера, что не так?
```js
{
		bytes: document.documentElement.outerHTML.length,
		scripts: Array.from(document.querySelectorAll('script')).reduce((acc,e) => acc+e.outerHTML.length,0),
		style: Array.from(document.querySelectorAll('style')).reduce((acc,e) => acc+e.outerHTML.length,0),
}
```

2020-01-10 23:44 UTC, mutantcornholio commented on src/lib/wpr/index.ts
> +            (p) => p.start().then(() => sleep(100)),
А подскажи, что эт за слип

2020-01-10 23:44 UTC, mutantcornholio commented on src/lib/wpr/index.ts
> +            const pageStructureSizesPromise = openPageWithRetries(page, site)
Почти полный клон того, что выше
`function fetchPageSizes(pageProfile: IPageProfile, filepath: string)`, например?

2020-01-10 23:44 UTC, mutantcornholio commented on src/lib/wpr/select.ts
> +                ? lodash.get(wprArchives[0], ['structureSizes', 'root'])
Зачем здесь `lodash.get`, если ты всё равно никак не защищаешься от отсутствия полей?

2020-01-10 23:44 UTC, mutantcornholio commented on src/lib/wpr/select.ts
> +                : jstat.stdev(wprArchives.map((wprArchive) => lodash.get(wprArchive, ['size'])), true),
Странная логика: «если два замера, покажи разницу, если больше — стандартное отклонение».
И значения разные (structureSizes.root vs. size) сравниваются в этих кейсах

2020-01-10 23:44 UTC, mutantcornholio commented on src/lib/wpr/select.ts
> +    sizePath: string[],
Давай будем иметь либо плоский список метрик с понятными айдишниками, а не lodash path?

2020-01-10 23:44 UTC, mutantcornholio commented on src/lib/wpr/select.ts
> +        case 'closestByScriptSize':
Это же размер инлайн-скриптов в HTML? Очень странный способ искать близкие замеры.

2020-01-13 09:31 UTC, alekzonder commented on src/lib/puppeteer/pageStructureSizes.ts
> +};
да, перемудрил, есть там момент по получению данных по размерам виджетов, но это сейчас не нужно, потом разберемся

переделал вот так через Blob чтобы размеры были честные, хотя может это и не настолько важно

```js
export const getPageStructureSizes = (page: puppeteer.Page): Promise<IPageStructureSizes> => {
    return page.evaluate(() => {
        const scripts = Array.from(document.querySelectorAll('script'));

        const scriptsByType = scripts.reduce((acc, element) => {
            (acc[element.type] = acc[element.type] || []).push(element);
            return acc;
        }, {} as {[index: string]: HTMLScriptElement[]});

        return {
            bytes: new Blob(Array.from(document.documentElement.outerHTML)).size,
            script: new Blob(
                scripts.map((e) => e.outerHTML),
            ).size,
            style: new Blob(
                Array.from(document.querySelectorAll('style')).map((e) => e.outerHTML),
            ).size,
            scripts: Object.entries(scriptsByType).reduce((acc, [scriptType, _elements]) => {
                acc[scriptType] = new Blob(
                    _elements.map((element) => element.outerHTML),
                ).size;
                return acc;
            }, {} as {[index: string]: number}),
        };
    });
};
```

2020-01-13 09:37 UTC, alekzonder commented on src/lib/wpr/index.ts
> +            (p) => p.start().then(() => sleep(100)),
стартует wpr record и стартует браузер, несколько раз ловил ситуации когда получаем ошибку в браузере, когда wpr еще не стартанул, хотя это быстро происходит

можно убрать, но стабильно будет работать после интеграции хуков для проверки страницы

с хуками будет так: 

- стартуем wpr record
- открываем бразуер
- запускается хук, который проверяет что страница корректно загрузилась - хук будет прям в porchmark.conf.js - если страница криво загрузилась, делаем несколько ретраев

еще можно проверять что у wpr record открыт порт, чтобы точно быть уверенным

2020-01-13 09:45 UTC, alekzonder commented on src/lib/wpr/index.ts
> +            const pageStructureSizesPromise = openPageWithRetries(page, site)
окай, переделал

2020-01-13 09:50 UTC, alekzonder commented on src/lib/wpr/select.ts
> +                ? lodash.get(wprArchives[0], ['structureSizes', 'root'])
странно выглядит

тут больше про что тулза не должно упасть, если вдруг что-то пошло не так

переделал

2020-01-13 10:02 UTC, alekzonder commented on src/lib/wpr/select.ts
> +                : jstat.stdev(wprArchives.map((wprArchive) => lodash.get(wprArchive, ['size'])), true),
да тут запутано получилось, но это вообще ни на что не влияет, потому что сравниваются просто все wpr-архивы в том порядке в котором записывались

запись про список сравниваемых wpr-архивов падает в логи 

-  и в случае если два wpr архива мы увидим какая у них разница - чтобы увидеть насколько разные страницы при сравнении
- а если wpr архивов больше 2х, то разницу между всеми мы посчитать не можем, а стандартное отклонение нам даст примерное понимание насколько они отличаются

в случае стандартного отклонения переделал на structureSizes.bytes
по сути тут можно поставить любое число и вообще ничего не вычислять

2020-01-13 10:24 UTC, alekzonder commented on src/lib/wpr/select.ts
> +        case 'closestByScriptSize':
это разные методы как искать похожие варианты, closetByHtmlSize показал лучшие результаты

гипотеза была в том что на точность сравнения влияет json содержащийся в странице, а его там может быть много и если подбирать wpr-архивы по размеру скриптов на страниц, то замеры будут точнее и за меньшее количество итераций

метод подбора остался, но можно убрать

2020-01-13 10:33 UTC, alekzonder commented on src/lib/wpr/select.ts
> +    sizePath: string[],
исправил, сделал такое enum

```js
export enum WprArchiveSizeTypes {
    WPR_ARCHIVE_SIZE,
    HTML_SIZE,
    INLINE_SCRIPT_SIZE,
}
```

и везде используется он

2020-01-13 10:36 UTC, alekzonder commented on src/lib/wpr/index.ts
> +            (p) => p.start().then(() => sleep(100)),
еще есть ошибки  при сравнении, но они ни на что не влияют 

при переключении wpr такое:

```
17:26:30.49 <error> Error: WebSocket is not open: readyState 3 (CLOSED)
```

это как раз открывается страница, а wpr replay еще не запустился, но так как workFarm ретраит при ошибках, то все ок

2020-01-13 10:37 UTC, alekzonder commented
@mutantcornholio /fixed

2020-01-14 06:34 UTC, mutantcornholio commented on src/lib/wpr/select.ts
> +        case 'closestByScriptSize':
Но апиари не оставляет этот json в DOM после иницаиализации)

2020-01-14 06:35 UTC, mutantcornholio commented on src/lib/wpr/select.ts
> +        case 'closestByScriptSize':
Как насчёт удалить этот метод вообще?

2020-01-14 06:38 UTC, alekzonder commented on src/lib/wpr/select.ts
> +        case 'closestByScriptSize':
Так это ж по странице без js, то что пришло сервера и wpr подбираются по этим размерам

2020-01-14 07:39 UTC, mutantcornholio approved these changes
Лан, давай дальше

2020-01-14 07:43 UTC, merged